### PR TITLE
ENH: Transition cookiecutter default branch name to `main`

### PR DESCRIPTION
**Pull request by jhlegarreta**
Transition cookiecutter default branch name to `main`.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Cross-referencing issue #117.

**Review by dzenanz — APPROVED** [review]
Looks good. I assume you tried it and it works?

**Comment by jhlegarreta** [comment]
> I assume you tried it and it works?

I didn't, :pray:. I trusted the CI builds for doing so.

**Comment by dzenanz** [comment]
Perhaps use it to create a new module in your user space, to make sure everything works as expected?

**Comment by dzenanz** [comment]
I ran this, and pushed the result to https://github.com/dzenanz/ModuleTest. The checks seem to be working fine: https://github.com/dzenanz/ModuleTest/runs/3244841832. Good to merge.

**Comment by jhlegarreta** [comment]
:100: Awesome @dzenanz. Many thanks for having given this a try !

**Review by thewtex — APPROVED** [review]
@jhlegarreta @dzenanz thank you so much!

**Pull request merged**
