### PR TITLE
STYLE: Conform to the ITK SW Guide when reporting in tests.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Conform to the ITK SW Guide when reporting in tests:
- Write explicitly that arguments are missing.
- Write explicitly that the test has finished.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
True. Having a look at the build history and the commits involved, I do not see any reasonable explanation:
https://circleci.com/gh/InsightSoftwareConsortium/ITKModuleTemplate

May be the baseline just needs to be updated?

**Comment by dzenanz** [comment]
Maybe some change in ITK affected the test? In that case updating the baseline should be enough.

**Comment by jhlegarreta** [comment]
46fe616 updates the `itkNormalDistributionImageSourceTestOutput.mha.sha512` content-link. Let's see if that makes itk.

**Comment by thewtex** [comment]
I think we have to do a git bisect on ITK.

**Comment by thewtex** [comment]
bisect follow-up in #47

**Comment by thewtex** [comment]
Given that the failing test has been addressed in #47 , could the baseline change in this patch be removed?

**Comment by jhlegarreta** [comment]
Thanks @thewtex ! 2a01a1d rebased on master.

**Comment by thewtex** [comment]
https://open.cdash.org/testDetails.php?test=734885898&build=5762438

`itkNormalDistributionImageSourceTest` is still failing -- I think we remove the NormalDistributionImageSource since we have "MyFilter". The extra code is annoying to remove when creating your own module, anyway...

**Comment by jhlegarreta** [comment]
c234ace rebased on master.

**Comment by jhlegarreta** [comment]
`itkNormalDistributionImageSourceTest` still failing:

```
80% tests passed, 1 tests failed out of 5

Label Time Summary:
ModuleTemplate    =   0.36 sec*proc (5 tests)

Total Test time (real) =   0.20 sec

The following tests FAILED:
	  5 - itkNormalDistributionImageSourceTest (Failed)
```

If we want to wait, builds should be green once #49 gets addressed. Otherwise, I think it is safe to merge.

**Comment by thewtex** [comment]
Rebase on `master` for improved CI?

**Comment by jhlegarreta** [comment]
3789d81 rebased on master.

**Pull request merged**
