### PR TITLE
ENH: Update CI builds systems from Ubuntu 18.04 to 20.04

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Review by jhlegarreta — APPROVED** [review]

**Comment by thewtex** [comment]
There are KWStyle warnings to address in KWStyle -> ITK before this update:

https://open.cdash.org/viewBuildError.php?type=1&buildid=7145449

```
KWStyle/kwsCheckLineLength.cxx:83:27: warning: '%ld' directive writing between 1 and 20 bytes into a region of size 10 [-Wformat-overflow=]
```

```

Warning | KWStyle/kwsCheckLineLength.cxx:83:26: note: directive argument in the range [-9223372036854775808, 9223372036854775806]
-- | --
```

**Review by dzenanz — COMMENTED** [review]
I guess this is ready now?

**Comment by thewtex** [comment]
KWStyle needs to be patched:

https://github.com/Kitware/KWStyle

Then updated in ITK.

**Comment by dzenanz** [comment]
https://github.com/InsightSoftwareConsortium/ITK/pull/2526 should fix KWStyle warnings.

**Comment by thewtex** [comment]
@dzenanz awesome!!

**Comment by thewtex** [comment]
:clap: @dzenanz , addressed with 5.2.1

**Pull request merged**
