### PR TITLE
ENH: Cache the Homebrew packages

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
CC: @jbvimort @phcerdan

**Comment by phcerdan** [comment]
Thanks @thewtex! It does it for me, travis builds the [module](https://travis-ci.org/phcerdan/ITKIsotropicWavelets) in 40min now :D

**Comment by thewtex** [comment]
CC: @LucasGandel another build optimization

**Comment by phcerdan** [comment]
Ups, still having time issues, it seems that travis is not always able to use cache between builds. If I restart a failed build it passes, but timing-out on new commits.

It would be great to have an option for not generating python 3.4 bindings in travis/mac, raised here: https://github.com/InsightSoftwareConsortium/ITKPythonPackage/issues/66 . The build in appveyor for windows doesn't generate 3.4 bindings.

Thanks for this though, every minute helps!

**Pull request merged**
