### PR TITLE
BUG: Use a different name for each macOS wheel name

### PR DESCRIPTION
**Pull request by jhlegarreta**
- BUG: Use a different name for each macOS wheel name
- STYLE: Make the wheel names consistent

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
MacOS wheels might now be duplicated, i.e. all of them having the same contents. Which got me thinking, do we even need wheels for this template project?

**Comment by jhlegarreta** [comment]
> MacOS wheels might now be duplicated, i.e. all of them having the same contents.

Not sure if I see this, unless you mean those of the template vs. the module.

> Which got me thinking, do we even need wheels for this template project?

:shrug: Maybe yes to generate a remote? Maybe @thewtex can tell us better.

**Comment by thewtex** [comment]
The wheels can be helpful to validate the template. Even if they are not uploaded to PyPI, they are available for examination in the GitHub Web UI.

**Review by thewtex — APPROVED** [review]
@jhlegarreta thanks!

**Pull request merged**
