### PR TITLE
Adding Initial configurations for Travis CI

### PR DESCRIPTION
**Pull request by blowekamp**

### CODE REVIEW

**Comment by thewtex** [comment]
@blowekamp It looks like the TravisCI service is enabled, but there is not a build link on the PR?

**Comment by blowekamp** [comment]
There is a bunch of particular C++11 code in this EXAMPLE module that makes it not portable or general. What compiler does this code actually work on?

**Comment by thewtex** [comment]
This example requires C++11. 

Many external module have special requirements or dependencies, which is why they have their own configuration.

**Comment by blowekamp** [comment]
This module does not compile any where.

**Pull request closed without merging**
