### PR TITLE
GitHub actions build test package

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
@hjmjohnson @mseng10

**Comment by thewtex** [comment]
@hjmjohnson @mseng10 please take a look.

For existing remotes, we can add this file unaltered (the results from evaluating the template) to the repository at *.github/workflows/build-test-package.yml*.

https://gist.github.com/thewtex/aab3f401b27dfd262e508cf1019853f0

@jhlegarreta @DVigneault would be interested know if these instructions work well for upgrading CI for ITKSubdivisionQuadEdgeMeshFilter.

**Comment by thewtex** [comment]
> Not sure why the ITK Python Package PyPI upload documentation link was removed, but I assume you have some reason for that.

Good idea -- we should keep that documentation for initial PyPI setup and package upload -- I will amend with these docs.

**Comment by thewtex** [comment]
> Good idea -- we should keep that documentation for initial PyPI setup and package upload -- I will amend with these docs.

On second thought, I will move these docs to that page.

**Comment by thewtex** [comment]
> On second thought, I will move these docs to that page.

Added here: https://github.com/InsightSoftwareConsortium/ITKPythonPackage/pull/142

**Comment by jhlegarreta** [comment]
> @jhlegarreta @DVigneault would be interested know if these instructions work well for upgrading CI for ITKSubdivisionQuadEdgeMeshFilter.

I apologize 🙏 , but I will not be able to test it Matt.

**Comment by thewtex** [comment]
> I apologize ￼ , but I will not be able to test it Matt.

Absolutely no problem, Jon Haitz.

I created a PR here:

  https://github.com/InsightSoftwareConsortium/ITKSubdivisionQuadEdgeMeshFilter/pull/25

@hjmjohnson @mseng10, note, to enable builds on the initial pull request, the branch has to be from a repository instead of a fork.

I deleted most Appveyor builds for remote modules.

**Comment by DVigneault** [comment]
@thewtex Excellent!!  This looks like a great leap forward--thank you for putting this together!!

**Pull request merged**
