### PR TITLE
ENH: Build Python 3.9 Python packages

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Review by jhlegarreta — APPROVED** [review]

**Review by dzenanz — APPROVED** [review]
If the CI builds succeed, great. Has something change regarding Python 3.9 over the last few days?

**Comment by thewtex** [comment]
The CI builds depend on https://github.com/scikit-build/scikit-ci-addons/pull/92 , which is now merged.

**Comment by dzenanz** [comment]
Should we also update [Python version for the generated modules](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/build-test-package.yml#L134)?

**Comment by thewtex** [comment]
> Should we also update Python version for the generated modules?

These are updated, correct?

**Comment by dzenanz** [comment]
Maybe I had an older version checked out or something.

**Pull request merged**
